apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: hello-tilt-java

namespace: default

resources:
  - microservice-deployment.yaml
  - microservice-service.yaml
  - database-deployment.yaml
  - database-service.yaml

configMapGenerator:
  - name: microservice-configmap
    literals:
      - DEFAULT_MESSAGE=Hands-on Tilt with Java.
  - name: database-configmap
    literals:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
