apiVersion: v1
kind: Service
metadata:
  name: hello-tilt-java
  labels:
    type: microservice
spec:
  selector:
    type: microservice
  type: ClusterIP
  sessionAffinity: None
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
