apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  env: dev

bases:
  - ../../base

resources:
  - hoverfly-deployment.yaml
  - hoverfly-service.yaml

configMapGenerator:
  - name: microservice-configmap
    behavior: merge
    files:
      - microservice.properties
    literals:
      - DEFAULT_MESSAGE=Hands-on Tilt with Java (DEV).
      - PORT=8080
