apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-tilt-go
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-tilt-go
  template:
    metadata:
      labels:
        app: hello-tilt-go
    spec:
      containers:
      - name: hello-tilt-go
        image: lreimer/hello-tilt-go
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"
        env:
          - name: PORT
            value: "9090"
        ports:
        - name: http
          containerPort: 9090
