apiVersion: v1
kind: Service
metadata:
  name: hello-tilt-go
spec:
  selector:
    app: hello-tilt-go
  type: ClusterIP
  sessionAffinity: None
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http
