apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  env: prod

bases:
  - ../../base

patchesStrategicMerge:
  - 4-replicas.yaml
  - probes.yaml

patchesJson6902:
  - target:
      version: v1
      kind: Service
      name: hello-tilt-java
    path: loadbalancer.yaml

configMapGenerator:
  - name: microservice-configmap
    behavior: merge
    files:
      - microservice.properties
    literals:
      - DEFAULT_MESSAGE=Hands-on Tilt with Java (PROD).
      - PORT=8080
